image: node:20-slim@sha256:cb4abfbba7dfaa78e21ddf2a72a592e5f9ed36ccf98bdc8ad3ff945673d288c2

before_script:
  - npm ci

cache:
  paths:
    - node_modules/

test:
  script:
    - npm run lib:build

deploy:
  script:
    - npm run lib:build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish
  only:
    - tags
  artifacts:
    paths:
      - dist/
