image: node:20-slim

before_script:
  - npm ci

cache:
  paths:
    - node_modules/

deploy:
  script:
    - npm run lib:build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish
  only:
    - tags
  artifacts:
    paths:
      - dist/
