image: node:20-slim@sha256:c2003782d629fdd0b2ca54b469069388d013304843034ba1b4fdf65040ed8f65

before_script:
  - npm ci

cache:
  paths:
    - node_modules/

test:
  script:
    - npm run lib:build

deploy:
  script:
    - npm run lib:build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish
  only:
    - tags
  artifacts:
    paths:
      - dist/
